name: Foundation Deploy (Pulumi Up)

on:
  workflow_dispatch:
    inputs:
      stack:
        description: Pulumi stack to deploy
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      aws-region:
        description: AWS region credentials default (should match stack config)
        required: true
        default: us-west-2
        type: string

permissions:
  id-token: write
  contents: read

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  up:
    environment: ${{ inputs.stack }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (workspace)
        run: pnpm -w install

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::123456789012:role/GitHubOIDCDeployRole
          role-session-name: gh-actions-foundation-up
          aws-region: ${{ inputs.aws-region }}

      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          work-dir: apps/foundation
          command: up
          stack-name: ${{ inputs.stack }}
          comment-on-pr: false
