name: Infra Preview

on:
  workflow_dispatch:
    inputs:
      stack:
        description: Pulumi stack to preview
        required: true
        default: dev
        type: choice
        options:
          - dev
          - staging
          - prod
      aws-region:
        description: AWS region credentials default (should match stack config)
        required: true
        default: us-west-2
        type: string

permissions:
  id-token: write
  contents: read

concurrency:
  group: infra-${{ inputs.stack }}
  cancel-in-progress: true

env:
  PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

jobs:
  preview:
    environment: ${{ inputs.stack }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.14.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (workspace)
        run: pnpm -w install

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gh-actions-infra-preview
          aws-region: ${{ inputs.aws-region }}

      - name: Who am I?
        run: aws sts get-caller-identity

      - name: Setup Pulumi CLI
        uses: pulumi/setup-pulumi@v2

      - name: Bootstrap Pulumi stack and config (if missing)
        working-directory: apps/infra
        run: |
          set -euo pipefail
          pulumi stack select ${{ inputs.stack }} || pulumi stack init ${{ inputs.stack }}
          pulumi config get aws:region >/dev/null 2>&1 || pulumi config set aws:region ${{ inputs.aws-region }}
          pulumi config get infra:web.cacheTtls.staticSeconds >/dev/null 2>&1 || pulumi config set infra:web.cacheTtls.staticSeconds 604800
          pulumi config get infra:web.cacheTtls.htmlSeconds >/dev/null 2>&1 || pulumi config set infra:web.cacheTtls.htmlSeconds 60
          pulumi config get infra:web.enableVersioning >/dev/null 2>&1 || pulumi config set infra:web.enableVersioning false
          pulumi config get infra:tags.project >/dev/null 2>&1 || pulumi config set --path infra:tags.project gitcraft
          pulumi config get infra:tags.component >/dev/null 2>&1 || pulumi config set --path infra:tags.component web
          pulumi config get infra:tags.environment >/dev/null 2>&1 || pulumi config set --path infra:tags.environment ${{ inputs.stack }}
          pulumi config get infra:tags.managed-by >/dev/null 2>&1 || pulumi config set --path infra:tags.managed-by pulumi

      - name: Install Pulumi program dependencies
        working-directory: apps/infra
        run: |
          set -euo pipefail
          pnpm install
          pulumi install

      - name: Pulumi Preview
        uses: pulumi/actions@v5
        with:
          work-dir: apps/infra
          command: preview
          stack-name: ${{ inputs.stack }}
          comment-on-pr: false
